# Site Settings
title: Gabriela Lugo
email: karla.gabriela.lb@gmail.com
description: >
  Gabriela's personal tech lifestyle website.
baseurl: "/"
url: "http://gabinas.github.io"
twitter_username: gabinas
github_username:  gabinas
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM